name: mediagrab_flutter
description: "MediaGrab - Video & Music Downloader"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  path: ^1.9.0
  file_picker: ^8.1.6
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/binaries/windows/
    - assets/binaries/macos/
    - assets/binaries/linux/
    - assets/cookies/cookies.txt
